itemsDataLocation = "../data/ItemReduced.csv"
serverByID = "../data/serversByID.csv"
rarefiedItems = "../data/rarefiedMaterials.csv"
scripValues = "../data/scripValues.csv"
scriptItemCosts = "../data/scripItemCosts.csv"